Exception in time_manipulation,unchecked_ll_calls module
Traceback (most recent call last):
  File "/conkas/vuln_finder/vulnerability_finder.py", line 51, in __analyse_modules
    vulns = vuln_finder.available_modules[vuln_module_key](self._traces, self._find_all)
KeyError: 'time_manipulation,unchecked_ll_calls'
Exception in time_manipulation,unchecked_ll_calls module
Traceback (most recent call last):
  File "/conkas/vuln_finder/vulnerability_finder.py", line 51, in __analyse_modules
    vulns = vuln_finder.available_modules[vuln_module_key](self._traces, self._find_all)
KeyError: 'time_manipulation,unchecked_ll_calls'
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
Analysing /sb/0x864f58021ff09d7abfc2e960dd69c62ad2fc8794.sol:EBPtandardToken...
Analysing /sb/0x864f58021ff09d7abfc2e960dd69c62ad2fc8794.sol:StandardToken...
Analysing /sb/0x864f58021ff09d7abfc2e960dd69c62ad2fc8794.sol:Token...
Nothing to analyse
