{
    "errors": [
        "Traceback (most recent call last):\n  File \"/usr/local/lib/python3"
    ],
    "fails": [],
    "findings": [],
    "infos": [],
    "parser": {
        "id": "mythril-0.24.7",
        "mode": "solidity",
        "version": "2024/03/24"
    },
    "tool_args": "--modules ArbitraryDelegateCall"
}
