Exception in time_manipulation,unchecked_ll_calls module
Traceback (most recent call last):
  File "/conkas/vuln_finder/vulnerability_finder.py", line 51, in __analyse_modules
    vulns = vuln_finder.available_modules[vuln_module_key](self._traces, self._find_all)
KeyError: 'time_manipulation,unchecked_ll_calls'
Exception in time_manipulation,unchecked_ll_calls module
Traceback (most recent call last):
  File "/conkas/vuln_finder/vulnerability_finder.py", line 51, in __analyse_modules
    vulns = vuln_finder.available_modules[vuln_module_key](self._traces, self._find_all)
KeyError: 'time_manipulation,unchecked_ll_calls'
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
Analysing /sb/0x0676c860e11ea7b53c09bd7f2adb70fe81c8dd1e.sol:BoomerangLiquidity...
Analysing /sb/0x0676c860e11ea7b53c09bd7f2adb70fe81c8dd1e.sol:ERC20Interface...
Nothing to analyse
Analysing /sb/0x0676c860e11ea7b53c09bd7f2adb70fe81c8dd1e.sol:Owned...
Analysing /sb/0x0676c860e11ea7b53c09bd7f2adb70fe81c8dd1e.sol:P3D...
Nothing to analyse
